Update bitbucket api
JeroenMols/GitAsMaven pull request #5
Opened 2020-01-27 17:53 UTC by francescogatto

Updates to v2 api of bitbucket and removing unique for gradle compatibilty

2020-01-27 19:20 UTC, JeroenMols approved these changes
Thanks for contributing this, looks good to me!

How have you tested this?

2020-01-27 19:20 UTC, JeroenMols commented on publish-bitbucket.gradle
> +        return (200 == responseCode || 404 == responseCode)
Why do you treat 404 as a success?

2020-01-27 19:21 UTC, JeroenMols requested changes
Please look into the 404 and answer my question on how you tested this.

2020-01-28 08:48 UTC, francescogatto commented on publish-bitbucket.gradle
> +        return (200 == responseCode || 404 == responseCode)
my mistake! it can be removed :)

2020-01-28 18:40 UTC, JeroenMols commented
Please update the pull request with the change and I'll make sure it gets
merged

On Tue, 28 Jan 2020 at 09:48, Francesco Gatto <notifications@github.com>
wrote:

> *@francescogatto* commented on this pull request.
> ------------------------------
>
> In publish-bitbucket.gradle
> <https://github.com/JeroenMols/GitAsMaven/pull/5#discussion_r371669614>:
>
> > @@ -91,7 +88,7 @@ def urlExists(String repositoryUrl) {
>            throw new RuntimeException("Unauthorized BitBucket user - please provide valid username and password in gradle.properties file")
>          }
>
> -        return (200 == responseCode)
> +        return (200 == responseCode || 404 == responseCode)
>
> my mistake! it can be removed :)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/JeroenMols/GitAsMaven/pull/5?email_source=notifications&email_token=ABQG4FJK26OAEYLHSETK3C3Q77WOHA5CNFSM4KMFPB7KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCTIHCEI#discussion_r371669614>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABQG4FK2VX7IYV566VFLZ5DQ77WOHANCNFSM4KMFPB7A>
> .
>

2020-01-28 22:29 UTC, francescogatto commented
I think I did it! 💃

2020-01-30 09:13 UTC, JeroenMols approved these changes

2020-01-30 09:14 UTC, merged